### ISSUE TITLE
Link

### ISSUE THREAD

**Issue by martinzerty** [McGuire00/Ssense-Sneaker-Bot#1]
Hello, 
I would like to know what type of link to insert.
is it something like: https://www.nike.com/launch/t/{name-of-shoe} or another one?

Thank you

**Comment by McGuire00** [comment]
> Hello,
> I would like to know what type of link to insert.
> is it something like: [https://www.nike.com/launch/t/{name-of-shoe}](https://www.nike.com/launch/t/%7Bname-of-shoe%7D) or another one?
> 
> Thank you

You would insert the link to the shoe you are trying to bot. For example: https://www.ssense.com/en-us/men/product/nike/black-ndstrkt-am-95-sneakers/7139581

**Comment by martinzerty** [comment]
Okay, thanks a lot, I will try again

**Comment by martinzerty** [comment]
I always have this problem:
`Traceback (most recent call last):
  File "sssence.py", line 215, in <module>
    shoe = Ssense()
  File "sssence.py", line 38, in __init__
    self.get_sku()    # gets product sku needed to check inventory and atc
  File "sssence.py", line 48, in get_sku
    shoe_info = self.soup.find('div', attrs={'class': 'pdp__redesign view'}).find('script')
AttributeError: 'NoneType' object has no attribute 'find'`
I have insert the link you shared and entered the size 9.
PS: I just renamed the file "sssence.py" 🙊

**Comment by McGuire00** [comment]
I am unable to replicate the error. It works perfectly fine for me
`10:17:27:879752 CST :: Welcome
Enter link to product...https://www.ssense.com/en-us/men/product/nike/black-ndstrkt-am-95-sneakers/7139581
Please enter shoe size...9
10:17:32:671654 CST :: Getting product information for Black NDSTRKT AM 95 Sneakers
10:17:32:672273 CST :: US 9 = IT 42 - Only 1 remaining 9_211011M23720303
10:17:33:204270 CST :: cart quanitity = 1
10:17:33:204345 CST :: Black NDSTRKT AM 95 Sneakers size US 9 has been added to your cart
10:17:33:818513 CST :: Logged in`

**Comment by McGuire00** [comment]
> I always have this problem:
> `Traceback (most recent call last): File "sssence.py", line 215, in <module> shoe = Ssense() File "sssence.py", line 38, in __init__ self.get_sku() # gets product sku needed to check inventory and atc File "sssence.py", line 48, in get_sku shoe_info = self.soup.find('div', attrs={'class': 'pdp__redesign view'}).find('script') AttributeError: 'NoneType' object has no attribute 'find'`
> I have insert the link you shared and entered the size 9.
> PS: I just renamed the file "sssence.py" 🙊

Hey, I am unable to recreate the error you mentioned. its working totally fine for me.

**Comment by martinzerty** [comment]
Oh, okay. Thank you, I will work on it.

**Comment by McGuire00** [comment]
> Oh, okay. Thank you, I will work on it.

I was able to replicate the error and made some changes

**Comment by martinzerty** [comment]
Hello again, I made print `self.soup` and it actualy is a recapcha page 😢 . Who is it possible?

**Comment by martinzerty** [comment]
> > Oh, okay. Thank you, I will work on it.
> 
> I was able to replicate the error and made some changes

Oh cool, you changed the file in the repostory?

**Comment by McGuire00** [comment]
> > > Oh, okay. Thank you, I will work on it.
> > 
> > 
> > I was able to replicate the error and made some changes
> 
> Oh cool, you changed the file in the repostory?

Yes, get the updated script.

**Comment by martinzerty** [comment]
Yes thank you,  I did it but it doesnt work.... I printed the `self.soup` and it show me code of a recapcha :( 
I already had this error but doesnt know why it shows it and how to make it work anyway.

**Comment by martinzerty** [comment]
I copy the code of the soup and paste it i an HTML:
<img width="1042" alt="Capture d’écran 2021-03-19 à 18 06 40" src="https://user-images.githubusercontent.com/64594930/111817085-dd7c6880-88dd-11eb-997a-032de36bf0c7.png">

**Comment by McGuire00** [comment]
> I copy the code of the soup and paste it i an HTML:
> <img alt="Capture d’écran 2021-03-19 à 18 06 40" width="1042" src="https://user-images.githubusercontent.com/64594930/111817085-dd7c6880-88dd-11eb-997a-032de36bf0c7.png">

I do not understand what you are asking me. Why are you trying to print self.soup

**Comment by martinzerty** [comment]
Oh yes sorry, I made it because it said the same thing: 
`self.product_name = self.soup.find('h2', attrs={'class':'pdp-product-title__name s-text'}).text.strip()
AttributeError: 'NoneType' object has no attribute 'text'` so I wanded to see what was in `self.soup`

**Comment by McGuire00** [comment]
I do not run into any captcha or the issue you have mentioned. I would have to be able to view your screen to get to the bottom of the issue, because on my end everything works.

**Comment by McGuire00** [comment]
Try tweaking the headers

**Comment by martinzerty** [comment]
This is the entire result:
<img width="1104" alt="Capture d’écran 2021-03-19 à 18 30 23" src="https://user-images.githubusercontent.com/64594930/111819912-2c77cd00-88e1-11eb-905d-93cc0ba67ede.png">
I also tried to change default navigator because it said : _Your browser does not support cookies_ on the html code of `soup`but it doesnt change.

**Comment by McGuire00** [comment]
Are you able to view the product page in a regular browser?

**Comment by martinzerty** [comment]
Yes, and I even found the `pdp-product-title__name s-text`object

**Comment by McGuire00** [comment]
The only explanation I can think of in response to the error message you are receiving is because of your headers. Are you sure you did not change them?

**Comment by McGuire00** [comment]
I get the same error you do when I remove the headers.

**Comment by martinzerty** [comment]
I am sorry but I didnt understand what are the headers🥴

**Comment by McGuire00** [comment]
`self.headers = {
        'user-agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 11_2_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.192 Safari/537.36'
        }`

**Comment by martinzerty** [comment]
Ah okay right thank you, I will try.

**Comment by martinzerty** [comment]
I removed it and it doesnt change. I will try with something other.

**Comment by McGuire00** [comment]
Open google chrome developer window and look at the request when the product page is called. View the headers and adjust the self.headers variable accordingly, and that should fix your issue.

**Comment by martinzerty** [comment]
I entered this: `Mozilla/5.0 (Linux; Android 6.0; Nexus 5 Build/MRA58N) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Mobile Safari/537.36` as shown below:

<img width="1436" alt="Capture d’écran 2021-03-19 à 19 26 53" src="https://user-images.githubusercontent.com/64594930/111826531-1241ed00-88e9-11eb-83df-284856a8fb49.png">

But it doesnt still work

**Comment by martinzerty** [comment]
...and also tried with `Mozilla/5.0 (Macintosh; Intel Mac OS X 11.2; rv:86.0) Gecko/20100101 Firefox/86.0as shown in firefox but still get the error....

**Comment by McGuire00** [comment]
Play around with other parameters in the headers section. I am confused as to why it does not work for you. I have tested it on different systems and it works.

**Comment by martinzerty** [comment]
Hmmm, I will think about it and will try in a new system

**Comment by McGuire00** [comment]
Hey, try the updated version and let me know.
